const quizData = [
  {
    id: 1,
    questiontype: "freeques",
    question: "4+5",
    answer: 9,
    useranswer: null,
  },
  {
    id: 2,
    questiontype: "mcq",
    question: "Which planet is known as the 'Red Planet'?",
    options: ["Jupiter", "Mars", "Venus", "Saturn"],
    answer: "Mars",
    useranswer: null,
  },
  {
    id: 3,
    questiontype: "freeques",
    question: "12/4",
    answer: 3,
    useranswer: null,
  },
  {
    id: 4,
    questiontype: "fillintheblank",
    question_start_word: "It",
    answer: ["annoys", "pleases", "annoys"],
    question_end_word: "Rainy Days",
    useranswer: null,
  },
  {
    id: 5,
    questiontype: "freeques",
    question: "8+2",
    answer: 10,
    useranswer: null,
  },
  {
    id: 6,
    questiontype: "fillintheblank",
    question_start_word: "We",
    answer: ["enjoy", "detest", "enjoy"],
    question_end_word: "Cooking",
    useranswer: null,
  },
  {
    id: 7,
    questiontype: "freeques",
    question: "6*6",
    answer: 36,
    useranswer: null,
  },
  {
    id: 8,
    questiontype: "mcq",
    question: "What is the capital of Japan?",
    options: ["Beijing", "Tokyo", "Seoul", "Bangkok"],
    answer: "Tokyo",
    useranswer: null,
  },
  {
    id: 9,
    questiontype: "mcq",
    question: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Central Process Unit",
      "Central Processor Unit",
    ],
    answer: "Central Processing Unit",
    useranswer: null,
  },
  {
    id: 10,
    questiontype: "mcq",
    question: "Who is the author of 'To Kill a Mockingbird'?",
    options: ["Harper Lee", "J.K. Rowling", "George Orwell", "Mark Twain"],
    answer: "Harper Lee",
    useranswer: null,
  },
  {
    id: 11,
    questiontype: "fillintheblank",
    question_start_word: "He",
    answer: ["appreciates", "abhors", "appreciates"],
    question_end_word: "Reading",
    useranswer: null,
  },
  {
    id: 12,
    questiontype: "mcq",
    question: "What is the largest ocean on Earth?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      "Pacific Ocean",
    ],
    answer: "Pacific Ocean",
    useranswer: null,
  },
  {
    id: 13,
    questiontype: "mcq",
    question: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Claude Monet",
    ],
    answer: "Leonardo da Vinci",
    useranswer: null,
  },
  {
    id: 14,
    questiontype: "fillintheblank",
    question_start_word: "I",
    answer: ["hate", "love", "hate"],
    question_end_word: "Soccer",
    useranswer: null,
  },
  {
    id: 15,
    questiontype: "fillintheblank",
    question_start_word: "She",
    answer: ["likes", "dislikes", "likes"],
    question_end_word: "Dancing",
    useranswer: null,
  },
  {
    id: 16,
    questiontype: "fillintheblank",
    question_start_word: "They",
    answer: ["prefer", "loathe", "prefer"],
    question_end_word: "Traveling",
    useranswer: null,
  },
  {
    id: 17,
    questiontype: "fillintheblank",
    question_start_word: "You",
    answer: ["adore", "despise", "adore"],
    question_end_word: "Shopping",
    useranswer: null,
  },
  {
    id: 18,
    questiontype: "mcq",
    question: "Which country is known as the 'Land of the Rising Sun'?",
    options: ["China", "Japan", "South Korea", "Vietnam"],
    answer: "Japan",
    useranswer: null,
  },
  {
    id: 19,
    questiontype: "fillintheblank",
    question_start_word: "It",
    answer: ["annoys", "pleases", "annoys"],
    question_end_word: "Rainy Days",
    useranswer: null,
  },
  {
    id: 20,
    questiontype: "fillintheblank",
    question_start_word: "You",
    answer: ["adore", "despise", "adore"],
    question_end_word: "Shopping",
    useranswer: null,
  },
];

export default quizData;
